version: '3.8'

services:
  app:
    image: gabim23/prueba37:latest
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stepxDatabase?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_MAIL_PASSWORD: "tuec lbpt fppw evxs"
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop #update antes
      SPRING_SERVER_PORT: 8443
    ports:
      - "8443:8443"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: stepxDatabase
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: